name: test

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: setup node
      uses: actions/setup-node@v3
    - name: run npm ci
      run: npm ci
    - name: install playwright dependencies
      run: npx playwright install --with-deps
    - name: run playwright test
      run: xvfb-run --auto-servernum -- npm run test
    - name: upload playwright test report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report
        retention-days: 1
    - name: deploy to github pages
      if: github.actor != 'dependabot[bot]'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: playwright-report
